# Generated by Django 2.1.2 on 2018-10-12 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('street', models.CharField(max_length=64)),
                ('housenumber', models.PositiveIntegerField(blank=True)),
                ('city', models.CharField(max_length=64)),
                ('psc', models.PositiveIntegerField(blank=True)),
                ('opensAt', models.TimeField()),
                ('closesAt', models.TimeField()),
                ('capacity', models.PositiveSmallIntegerField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('place_of_origin', models.CharField(blank=True, max_length=64)),
                ('quality', models.CharField(blank=True, max_length=64)),
                ('taste_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeBean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('origin', models.CharField(blank=True, max_length=64)),
                ('aroma', models.CharField(blank=True, max_length=64)),
                ('acidity', models.PositiveSmallIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeContainsBeans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveIntegerField()),
                ('Coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kavarna.Coffee')),
                ('CoffeeBean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kavarna.CoffeeBean')),
            ],
        ),
        migrations.CreateModel(
            name='CoffeePreparation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('Coffee_list', models.ManyToManyField(to='kavarna.Coffee')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('surname', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('nick', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('surname', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('fav_coffee', models.ManyToManyField(to='kavarna.Coffee')),
                ('fav_preparation', models.ManyToManyField(to='kavarna.CoffeePreparation')),
                ('likes_cafe', models.ManyToManyField(to='kavarna.Cafe')),
            ],
        ),
        migrations.AddField(
            model_name='reaction',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kavarna.User'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kavarna.Cafe'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kavarna.Reaction'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kavarna.Evaluation'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kavarna.Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(to='kavarna.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kavarna.Cafe'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kavarna.User'),
        ),
        migrations.AddField(
            model_name='coffee',
            name='beans',
            field=models.ManyToManyField(through='kavarna.CoffeeContainsBeans', to='kavarna.CoffeeBean'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='offers_coffee',
            field=models.ManyToManyField(to='kavarna.Coffee'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kavarna.Owner'),
        ),
    ]
