# Generated by Django 2.1.2 on 2018-10-12 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kavarna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='preparation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kavarna.CoffeePreparation'),
        ),
    ]
