# Generated by Django 2.1.2 on 2018-10-12 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kavarna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeContainsBeans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='coffee',
            name='beans',
            field=models.ManyToManyField(through='kavarna.CoffeeContainsBeans', to='kavarna.CoffeeBean'),
        ),
        migrations.AddField(
            model_name='coffeecontainsbeans',
            name='Coffee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kavarna.Coffee'),
        ),
        migrations.AddField(
            model_name='coffeecontainsbeans',
            name='CoffeeBean',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kavarna.CoffeeBean'),
        ),
    ]
