# Generated by Django 2.1.2 on 2018-10-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kavarna', '0002_auto_20181012_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='beans',
            field=models.ManyToManyField(blank=True, through='kavarna.CoffeeContainsBeans', to='kavarna.CoffeeBean'),
        ),
    ]
