# Generated by Django 2.1.2 on 2018-10-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kavarna', '0002_auto_20181013_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
