# Generated by Django 2.1.2 on 2018-10-12 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kavarna', '0002_coffee_preparation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffeecontainsbeans',
            old_name='Coffee',
            new_name='coffee',
        ),
        migrations.RenameField(
            model_name='coffeecontainsbeans',
            old_name='CoffeeBean',
            new_name='coffeeBean',
        ),
    ]
