# Generated by Django 2.1.2 on 2018-11-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kavarna', '0003_auto_20181117_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='housenumber',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
