# Generated by Django 2.1.2 on 2018-10-12 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kavarna', '0003_auto_20181012_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='beans',
        ),
    ]
