# Generated by Django 2.0.5 on 2018-10-15 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kavarna', '0003_auto_20181013_0633'),
    ]

    operations = [
    ]
