# Generated by Django 2.1.2 on 2018-11-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kavarna', '0004_auto_20181117_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinker',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
