# Generated by Django 2.0.5 on 2018-10-21 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kavarna', '0004_auto_20181015_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drinker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('fav_coffee', models.ManyToManyField(to='kavarna.Coffee')),
                ('fav_preparation', models.ManyToManyField(to='kavarna.CoffeePreparation')),
                ('likes_cafe', models.ManyToManyField(to='kavarna.Cafe')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='fav_coffee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fav_preparation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='likes_cafe',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='user',
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(to='kavarna.Drinker'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kavarna.Drinker'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='drinker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kavarna.Drinker'),
        ),
    ]
