# Generated by Django 2.1.2 on 2018-10-12 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kavarna', '0004_remove_coffee_beans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('place_of_origin', models.CharField(blank=True, max_length=64)),
                ('quality', models.CharField(blank=True, max_length=64)),
                ('taste_description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='coffee',
            name='beans',
            field=models.ManyToManyField(blank=True, to='kavarna.CoffeeBean'),
        ),
        migrations.AlterField(
            model_name='coffeecontainsbeans',
            name='Coffee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kavarna.Coffee2'),
        ),
        migrations.AddField(
            model_name='coffee2',
            name='beans',
            field=models.ManyToManyField(blank=True, through='kavarna.CoffeeContainsBeans', to='kavarna.CoffeeBean'),
        ),
    ]
