# Generated by Django 2.0.5 on 2018-10-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kavarna', '0005_auto_20181021_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinker',
            name='email',
        ),
        migrations.RemoveField(
            model_name='drinker',
            name='name',
        ),
        migrations.RemoveField(
            model_name='drinker',
            name='surname',
        ),
        migrations.AddField(
            model_name='drinker',
            name='key',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
