# Generated by Django 2.1.2 on 2018-10-12 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kavarna', '0005_auto_20181012_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee2',
            name='beans',
        ),
        migrations.RemoveField(
            model_name='coffeecontainsbeans',
            name='Coffee',
        ),
        migrations.RemoveField(
            model_name='coffeecontainsbeans',
            name='CoffeeBean',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='beans',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='place_of_origin',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='taste_description',
        ),
        migrations.DeleteModel(
            name='Coffee2',
        ),
        migrations.DeleteModel(
            name='CoffeeContainsBeans',
        ),
    ]
