# Generated by Django 2.1.2 on 2018-10-12 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kavarna', '0006_auto_20181012_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeContainsBeans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='coffee',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='coffee',
            name='place_of_origin',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='coffee',
            name='quality',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='coffee',
            name='taste_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coffeecontainsbeans',
            name='Coffee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kavarna.Coffee'),
        ),
        migrations.AddField(
            model_name='coffeecontainsbeans',
            name='CoffeeBean',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kavarna.CoffeeBean'),
        ),
        migrations.AddField(
            model_name='coffee',
            name='beans',
            field=models.ManyToManyField(through='kavarna.CoffeeContainsBeans', to='kavarna.CoffeeBean'),
        ),
    ]
