# Generated by Django 2.1.2 on 2018-10-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kavarna', '0007_auto_20181012_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
