# Generated by Django 2.0.5 on 2018-10-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kavarna', '0008_auto_20181023_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='owner',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
