# Generated by Django 2.0.5 on 2018-10-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kavarna', '0010_auto_20181025_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
