# Generated by Django 2.0.5 on 2018-10-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kavarna', '0011_auto_20181025_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='psc',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
