# Generated by Django 2.0.5 on 2018-10-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kavarna', '0012_auto_20181025_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='closesAt',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='opensAt',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
